trigger:
  branches:
   include:
     - master
     - development
     - staging      
name: Deployment

concurrency: master

if hashFiles('**/_settings.json')==truename: deployment
on
  pull_request_review:
    types:
      - submitted
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: PR Check
      run: echo PR raised
